apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaiburr.fullname" . }}
  labels:
    {{- include "kaiburr.labels" . | nindent 4 }}
spec:
  #type: {{ .Values.service.type }}
  type: LoadBalancer 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kaiburr.selectorLabels" . | nindent 4 }}
